public class BOA implements FRB {

    public static void dispatchCash(){
        
    }
    
    public static void calcCI(){
        
    }
     public static void calcSI(){
        
    }
    public static void OpenTime(){
        
    }
    public static void CloseTime(){
        
    }
    public static void RepoRateCal(){
        
    }
     public static void ReverseRepoRateCal(){
        
    }
}