public class IntegeratingO2OHandler {

	//Write below clientId, clientSecret, username, password from Org B Destination Org)
	private final String clientId = '';
    private final String clientSecret = '';
    private final String username = 'amanmaindola@cloudanalogy.com';
    private final String password = 'Aman1234';
    
    public class resWrapper{
        public String id;
        public String access_token;
	}
    
    public class accountWrap {
		public string case_region;
		public String wName;
		public String wPhone;
		public accountWrap(String name, String phone){
			this.wName = name;
			this.wPhone = phone;
		}
	}
    
   
    
}