public class MyApexClass {
    public integer num1 {get; set;}
    public integer num2 {get; set;}
    public double result {get; set;}
    public string operation {get; set;}
    
    public void add(){
       
        
       
            result = num1 + num2;
        
       
        
    }
    public void sub(){
       
        
       
            result = num1 - num2;
        
       
        
    }
    
    
}