public class MyFirstClass {
	//Template
	//we'll define the property/attribute and functionaly of object. 
	
	//Instance variable or Member variable 
    public string name;
    public string size;
    public string color;
    public string address;
    
    // Function or Method
    public string doSendEmail(){
        // code to send an email. 
        
        return 'sent email successfully';
        
    }
    
    
    
    
    
}